spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devclass
    username: dev
    password: 1234   # ?? ????? ??
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate         # DDL? ?? ?? ? validate? ????
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

  # ?? ??: SQL ???? devclass_db.sql ?? ??
  sql:
    init:
      mode: never

jwt:
  secret: devclass-secret-key-must-be-at-least-256-bits-long-for-hs256
  expiration-ms: 86400000    # 24??

toss:
  secret-key: test_sk_zXLkKEypNArWmo50nX3lmeaxYG5R

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    com.devclass: DEBUG


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true